[env]
TERM = "xterm-256color"

[window]
opacity = 0.95
padding = { x = 5, y = 5 }
title = "Alacritty"
decorations = "None"

[font]
size = 12

[font.offset]
x = 0
y = -1

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[general]
import = [
    "~/.config/alacritty/themes/tokyo-night.toml"
]
