[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[colors.cursor]
text = "#1a1b26"
cursor = "#c0caf5"

[colors.vi_mode_cursor]
text = "#1a1b26"
cursor = "#c0caf5"

[colors.search.matches]
foreground = "#1a1b26"
background = "#e0af68" 

[colors.search.focused_match]
foreground = "#1a1b26"
background = "#9ece6a" 

[colors.hints.start]
foreground = "#1a1b26"
background = "#e0af68"

[colors.hints.end]
foreground = "#1a1b26"
background = "#9ece6a"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#1a1b26"
background = "#a9b1d6"

[colors.selection]
text = "CellForeground"
background = "#33467c"

[colors.normal]
black = "#15161e"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"

[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

[colors.dim]
black = "#333333"
red = "#f2777a"
green = "#99cc99"
yellow = "#ffcc66"
blue = "#6699cc"
magenta = "#cc99cc"
cyan = "#66cccc"
white = "#dddddd"
